In [1]:
# importing necessary packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from pprint import pprint

In [4]:
# Fetching data
students = pd.read_csv('../data/students.csv')
courses = pd.read_csv('../data/courses.csv')
instructors = pd.read_csv('../data/instructors.csv')
enrollments = pd.read_csv('../data/enrollments.csv')
grades = pd.read_csv('../data/grades.csv')

In [5]:
students

,Unnamed: 0,StudentID,StudentName,Age,Email,EnrollmentDate,Major
0,0,1,Alice,20,alice@school.com,2023-09-01,Computer Science
1,1,2,Bob,21,bob@school.com,2023-09-01,Biology
2,2,3,Charlie,19,charlie@school.com,2024-01-15,History
3,3,4,Diana,22,diana@school.com,2022-09-01,Art
4,4,5,Eve,23,eve@school.com,2023-01-10,Mathematics
5,5,6,Frank,20,frank@school.com,2024-02-01,Physics
6,6,7,Grace,21,grace@school.com,2023-09-15,Chemistry
7,7,8,Henry,19,henry@school.com,2024-03-01,English
8,8,9,Isabel,22,isabel@school.com,2023-08-20,Psychology
9,9,10,Jack,20,jack@school.com,2024-01-10,Economics
10,10,11,Kelly,24,kelly@school.com,2022-08-15,Sociology
11,11,12,Liam,18,liam@school.com,2024-09-01,Undecided
12,12,13,Mia,19,mia@school.com,2023-09-10,Computer Science
13,13,14,Noah,22,noah@school.com,2022-10-01,Biology
14,14,15,Olivia,20,olivia@school.com,2024-02-15,History
15,15,16,Peter,21,peter@school.com,2023-08-25,Art
16,16,17,Quinn,23,quinn@school.com,2023-01-20,Mathematics
17,17,18,Rose,20,rose@school.com,2024-03-10,Physics
18,18,19,Sam,19,sam@school.com,2023-09-05,Chemistry
19,19,20,Tina,22,tina@school.com,2022-11-01,English
20,20,21,Uma,21,uma21@school.com,2024-01-25,Psychology
21,21,22,Victor,20,victor@school.com,2023-08-15,Economics
22,22,23,Wendy,24,wendy@school.com,2022-09-20,Sociology
23,23,24,Xander,18,xander@school.com,2024-09-05,Undecided
24,24,25,Yara,19,yara@school.com,2023-10-01,Computer Science
25,25,26,Zane,22,zane@school.com,2022-12-01,Biology
26,26,27,Ava,20,ava@school.com,2024-02-20,History
27,27,28,Ben,21,ben@school.com,2023-09-25,Art
28,28,29,Clara,23,clara@school.com,2023-02-01,Mathematics
29,29,30,Dan,20,dan@school.com,2024-03-15,Physics
30,30,31,Ella,19,ella@school.com,2023-10-10,Chemistry
31,31,32,Finn,22,finn@school.com,2022-11-15,English
32,32,33,Gina,21,gina@school.com,2024-02-01,Psychology
33,33,34,Hank,20,hank@school.com,2023-08-30,Economics
34,34,35,Ivy,24,ivy@school.com,2022-10-05,Sociology
35,35,36,Jonah,18,jonah@school.com,2024-09-10,Undecided
36,36,37,Kara,19,kara@school.com,2023-11-01,Computer Science
37,37,38,Leo,22,leo@school.com,2022-12-15,Biology
38,38,39,Mila,20,mila@school.com,2024-03-01,History
39,39,40,Nate,21,nate@school.com,2023-09-30,Art
40,40,41,Omar,23,omar@school.com,2023-02-15,Mathematics
41,41,42,Pia,20,pia@school.com,2024-03-20,Physics
42,42,43,Raul,19,raul@school.com,2023-11-10,Chemistry
43,43,44,Sara,22,sara@school.com,2022-12-20,English
44,44,45,Tom,21,tom@school.com,2024-02-10,Psychology
45,45,46,Uma,20,uma46@school.com,2023-09-15,Economics
46,46,47,Vera,24,vera@school.com,2022-10-15,Sociology
47,47,48,Will,18,will@school.com,2024-09-15,Undecided
48,48,49,Xena,19,xena@school.com,2023-11-20,Computer Science
49,49,50,Yuri,22,yuri@school.com,2022-12-25,Biology
50,50,51,Zoe,20,zoe@school.com,2024-03-05,History
51,51,52,Adam,21,adam@school.com,2023-10-05,Art

In [12]:
result = pd.merge(students, enrollments, on='StudentID', how='inner')

In [13]:
result

,Unnamed: 0_x,StudentID,StudentName,Age,Email,EnrollmentDate,Major,Unnamed: 0_y,EnrollmentID,CourseID
0,0,1,Alice,20,alice@school.com,2023-09-01,Computer Science,0,1,101
1,0,1,Alice,20,alice@school.com,2023-09-01,Computer Science,1,2,108
2,1,2,Bob,21,bob@school.com,2023-09-01,Biology,2,3,102
3,1,2,Bob,21,bob@school.com,2023-09-01,Biology,3,4,105
4,2,3,Charlie,19,charlie@school.com,2024-01-15,History,4,5,103
5,2,3,Charlie,19,charlie@school.com,2024-01-15,History,19,20,107
6,3,4,Diana,22,diana@school.com,2022-09-01,Art,5,6,104
7,4,5,Eve,23,eve@school.com,2023-01-10,Mathematics,6,7,101
8,4,5,Eve,23,eve@school.com,2023-01-10,Mathematics,7,8,106
9,5,6,Frank,20,frank@school.com,2024-02-01,Physics,8,9,105
10,5,6,Frank,20,frank@school.com,2024-02-01,Physics,9,10,102
11,6,7,Grace,21,grace@school.com,2023-09-15,Chemistry,10,11,106
12,6,7,Grace,21,grace@school.com,2023-09-15,Chemistry,11,12,102
13,7,8,Henry,19,henry@school.com,2024-03-01,English,12,13,107
14,8,9,Isabel,22,isabel@school.com,2023-08-20,Psychology,13,14,109
15,8,9,Isabel,22,isabel@school.com,2023-08-20,Psychology,14,15,107
16,9,10,Jack,20,jack@school.com,2024-01-10,Economics,15,16,110
17,9,10,Jack,20,jack@school.com,2024-01-10,Economics,16,17,101
18,10,11,Kelly,24,kelly@school.com,2022-08-15,Sociology,17,18,111
19,10,11,Kelly,24,kelly@school.com,2022-08-15,Sociology,18,19,109
20,12,13,Mia,19,mia@school.com,2023-09-10,Computer Science,20,21,108
21,12,13,Mia,19,mia@school.com,2023-09-10,Computer Science,57,58,101
22,13,14,Noah,22,noah@school.com,2022-10-01,Biology,21,22,102
23,14,15,Olivia,20,olivia@school.com,2024-02-15,History,22,23,103
24,15,16,Peter,21,peter@school.com,2023-08-25,Art,23,24,104
25,16,17,Quinn,23,quinn@school.com,2023-01-20,Mathematics,24,25,101
26,17,18,Rose,20,rose@school.com,2024-03-10,Physics,25,26,105
27,18,19,Sam,19,sam@school.com,2023-09-05,Chemistry,26,27,106
28,19,20,Tina,22,tina@school.com,2022-11-01,English,27,28,107
29,20,21,Uma,21,uma21@school.com,2024-01-25,Psychology,28,29,109
30,21,22,Victor,20,victor@school.com,2023-08-15,Economics,29,30,110
31,22,23,Wendy,24,wendy@school.com,2022-09-20,Sociology,30,31,111
32,24,25,Yara,19,yara@school.com,2023-10-01,Computer Science,31,32,108
33,24,25,Yara,19,yara@school.com,2023-10-01,Computer Science,58,59,101
34,25,26,Zane,22,zane@school.com,2022-12-01,Biology,32,33,102
35,26,27,Ava,20,ava@school.com,2024-02-20,History,33,34,103
36,27,28,Ben,21,ben@school.com,2023-09-25,Art,34,35,104
37,28,29,Clara,23,clara@school.com,2023-02-01,Mathematics,35,36,101
38,29,30,Dan,20,dan@school.com,2024-03-15,Physics,36,37,105
39,30,31,Ella,19,ella@school.com,2023-10-10,Chemistry,37,38,106
40,31,32,Finn,22,finn@school.com,2022-11-15,English,38,39,107
41,32,33,Gina,21,gina@school.com,2024-02-01,Psychology,39,40,109
42,33,34,Hank,20,hank@school.com,2023-08-30,Economics,40,41,110
43,34,35,Ivy,24,ivy@school.com,2022-10-05,Sociology,41,42,111
44,36,37,Kara,19,kara@school.com,2023-11-01,Computer Science,42,43,108
45,36,37,Kara,19,kara@school.com,2023-11-01,Computer Science,59,60,101
46,37,38,Leo,22,leo@school.com,2022-12-15,Biology,43,44,102
47,38,39,Mila,20,mila@school.com,2024-03-01,History,44,45,103
48,39,40,Nate,21,nate@school.com,2023-09-30,Art,45,46,104
49,40,41,Omar,23,omar@school.com,2023-02-15,Mathematics,46,47,101
50,41,42,Pia,20,pia@school.com,2024-03-20,Physics,47,48,105
51,42,43,Raul,19,raul@school.com,2023-11-10,Chemistry,48,49,106
52,43,44,Sara,22,sara@school.com,2022-12-20,English,49,50,107
53,44,45,Tom,21,tom@school.com,2024-02-10,Psychology,50,51,109
54,45,46,Uma,20,uma46@school.com,2023-09-15,Economics,51,52,110
55,46,47,Vera,24,vera@school.com,2022-10-15,Sociology,52,53,111
56,48,49,Xena,19,xena@school.com,2023-11-20,Computer Science,53,54,108
57,49,50,Yuri,22,yuri@school.com,2022-12-25,Biology,54,55,102
58,50,51,Zoe,20,zoe@school.com,2024-03-05,History,55,56,103
59,51,52,Adam,21,adam@school.com,2023-10-05,Art,56,57,104